import LinearAlgebraInLean.Group
import LinearAlgebraInLean.Field
import LinearAlgebraInLean.Sum
import LinearAlgebraInLean.VectorSpace.Tactics

class VectorSpace (F: Field F) (V : Type) extends AbelianGroup V, SMul F V where
  one_mul : ∀ v: V, (1:F) • v = v := by vector_space_refold
  s_assoc : ∀ (r s: F) (v : V), r • (s • v) = (r * s) • v := by vector_space_refold; try intros; ac_nf
  s_distr_left : ∀ (r s : F) (v : V), (r+s)•v = (r•v) + (s•v) := by vector_space_refold
  s_distr_right : ∀ (r: F) (v w : V), r•(v+w) = (r•v) + (r•w) := by vector_space_refold

attribute[simp] VectorSpace.one_mul VectorSpace.s_assoc VectorSpace.s_distr_left VectorSpace.s_distr_right

instance : CoeSort (VectorSpace K V) Type where
  coe _ := V


namespace VectorSpace
variable {F V} [F: Field F] [V: VectorSpace F V]

@[simp] theorem smul_zero_right  (r : F) : r • (0: V) = 0 := by
  have h : r • (0 + (0:V)) = r • 0 + r • 0 := by rw [<-s_distr_right]
  have h : r • (0:V) = r • 0 + r • 0 := by simp [<-h]
  apply (Group.neutral_unique h.symm)

@[simp] theorem smul_zero_left (v : V) : (0:F) • v = 0 := by
  have := calc v
          _ = (1 + 0: F) • v := by simp
          _ = (1:F) • v + (0:F) • v := by rw [s_distr_left]
          _ = v + (0:F) • v := by simp
  apply Group.neutral_unique this.symm

@[simp] theorem smul_minus_left (x: F) (v : V) : (-x • v) = - (x•v) := by
  have : (0:F)•v = 0 := by simp
  have : (-x + x)•v = 0 := by simp
  have : -x • v + x • v = 0 := by rw[<-s_distr_left, this]
  apply Group.neg_unique_left this

@[simp] theorem smul_minus_right (x: F) (v : V) : (x • -v) = - (x•v) := by
  have := calc x • v + x • -v
    _ = x • (v + -v) := by simp [<-VectorSpace.s_distr_right]
    _ = 0 := by simp
  apply Group.neg_unique this

@[simp] theorem zero_div_free (r : F) (v : V) (h: r • v = 0) : r = 0 ∨ v = 0 := by
  by_cases hr: r = 0
  . left
    assumption
  . right
    have h₂ : v = (1:F) • v := by simp
    let rn: F.non_zeros := ⟨r,hr⟩
    have : rn⁻¹.val * rn = 1 := by rw [Field.mul_inverse_left]
    rw [<-this] at h₂
    rw [<-s_assoc] at h₂
    rw [h] at h₂
    rw [smul_zero_right] at h₂
    exact h₂


@[simp] theorem zero_mul {v: V}: (0: F) • v = 0 := by
  rw [<-Group.inverse_left 1, VectorSpace.s_distr_left]
  simp

@[simp] theorem mul_zero {μ : F}: μ • (0: V) = 0 := by
  have : μ • (0: V) + μ • 0 = μ • 0 := by simp
  apply Group.neutral_unique this

theorem _root_.Sum.const_vs [VectorSpace F S] {a: S}: sum (List.replicate n a) = (n: F) • a := by
  induction n with
    | zero => simp [nat_to_r1ng]
    | succ n h =>
      unfold List.replicate
      simp [nat_to_r1ng]
      unfold sum
      rw [h, One.one_is_ofNat]
      simp

theorem _root_.Sum.scalar [V: VectorSpace F S] {μ: F} {ls: List V}: sum (List.map (μ • .) ls) =  μ • sum ls := by
  induction ls with
    | nil => simp[sum]
    | cons a as h =>
      unfold List.map
      unfold sum
      simp
      congr

def linear_independent (F:Field F) [V: VectorSpace F V] (vs: List V) : Prop := ∀ (ls: List F) (_: ls.length = vs.length), sum (ls.zipWith (. • .) vs) = 0 -> ∀ l ∈ ls, l = 0

theorem emptyset_is_linear_independent : @linear_independent F V F V [] := by
  unfold linear_independent
  simp

@[simp] theorem sum_s_distr {vs: List V} {x: F} : sum (vs.map (fun v => x • v)) = x • sum vs := by -- maybe merge with Sum.sum_distr (same proof)
  induction vs with
  | nil =>
    unfold sum
    simp
  | cons i iss ih =>
    unfold sum
    simp[ih]

theorem List.zipWith_eraseIdx {α β γ : Type} (f : α → β → γ) :
    ∀ (xs : List α) (ys : List β) (i : Nat), List.zipWith f (xs.eraseIdx i) (ys.eraseIdx i) = (List.zipWith f xs ys).eraseIdx i := by
    intro xs
    induction xs with
    | nil => simp
    | cons x xs ih =>
      intro ys i
      cases ys with
      | nil => simp
      | cons y ys =>
        cases i with
        | zero => simp
        | succ i => simp[ih]

private theorem list_perm_refl {α : Type u} : ∀ xs : List α, xs.Perm xs -- generated by chatgpt
  | [] => List.Perm.nil
  | x :: xs => List.Perm.cons x (list_perm_refl xs)

theorem List.getElem_cons_eraseIdx_perm
    {α : Type u} (xs : List α) (i : Nat) (hi : i < xs.length) : --generated by chatgpt, simmilar theorem is in mathlib, but not in stdlib
    (xs[i]'hi :: xs.eraseIdx i).Perm xs := by
  induction xs generalizing i with
  | nil =>
      cases hi
  | cons x xs ih =>
      cases i with
      | zero =>
          change (x :: xs).Perm (x :: xs)
          exact list_perm_refl (x :: xs)
      | succ i =>
          have hi' : i < xs.length := by
            exact Nat.lt_of_succ_lt_succ (by simpa using hi)
          change (xs[i]'hi' :: x :: xs.eraseIdx i).Perm (x :: xs)
          exact List.Perm.trans
            (List.Perm.swap x (xs[i]'hi') (xs.eraseIdx i))
            (List.Perm.cons x (ih i hi'))

theorem v_is_lincomb_of_others_from_lin_dep [BEq V][LawfulBEq V][BEq F][EquivBEq F][LawfulBEq F]
        (vs: List V) (hl : ¬ @linear_independent F V F V vs) :
        ∃ i1:Nat, ∃h:i1 < vs.length, ∃ ls : List F, ls.length = vs.length - 1 ∧ vs[i1] = sum (ls.zipWith (. • .) (vs.eraseIdx i1)) := by
  unfold linear_independent at hl
  simp at hl
  have ⟨xs, h_xsLen, h_sumEq0, x1, h_x1InXs, h_x1Neq0⟩ := hl
  let i1 := xs.idxOf x1
  have h_i1LeXs : i1 < xs.length := List.idxOf_lt_length_of_mem h_x1InXs
  have h_x1Neq0 : x1 ≠ 0 := by simp[h_x1Neq0]
  let x1i' :=(⟨x1,h_x1Neq0⟩:F.non_zeros)⁻¹
  let x1i  := x1i'.val
  have x1_inv : x1i * x1 = 1 := by simp[x1i,x1i']

  have h_i1LeVs : i1 < vs.length := by simp[<-h_xsLen, h_i1LeXs]

  let ys := (xs.eraseIdx i1).map (fun x => -x1i*x)
  let v1 := vs[i1]

  exists i1
  exists h_i1LeVs
  exists ys

  constructor
  . simp[ys,<-h_xsLen]
    apply xs.length_eraseIdx_of_lt
    exact h_i1LeXs
  . apply Eq.symm
    have h_i1LeZip: i1 < (List.zipWith (fun x v => x • v) xs vs).length := by simp[<-h_xsLen, h_i1LeXs]
    have : x1 = xs[i1] := by
      symm
      have hbeq : (xs[i1] == x1) = true := by
        simpa [i1, List.idxOf] using
          (List.findIdx_getElem
            (p := fun y => y == x1))
      have hget : xs[i1]'h_i1LeXs = x1 := by
        exact eq_of_beq hbeq
      exact hget


    have : x1 • v1 = (List.zipWith (fun x v => x • v) xs vs)[i1] := by simp[v1,this]

    calc
      sum (List.zipWith (fun x1 x2 => x1 • x2) ys (vs.eraseIdx i1))
      _ = sum (List.zipWith (fun x v => (-x1i*x) • v) (xs.eraseIdx i1) (vs.eraseIdx i1)) := by simp[ys, List.zipWith_map_left]
      _ = sum (List.map (fun v => -x1i • v) (List.zipWith (fun x v => x • v) (xs.eraseIdx i1) (vs.eraseIdx i1))) := by simp
      _ = -x1i • sum (List.zipWith (fun x v => x • v) (xs.eraseIdx i1) (vs.eraseIdx i1)) := by rw[sum_s_distr]
      _ = -x1i • ((-x1 • v1) + x1 • v1 + sum (List.zipWith (fun x v => x • v) (xs.eraseIdx i1) (vs.eraseIdx i1))) := by simp
      _ = -x1i • ((-x1 • v1) + (x1 • v1 + sum (List.zipWith (fun x v => x • v) (xs.eraseIdx i1) (vs.eraseIdx i1)))) := by rw [V.assoc]
      _ = -x1i • ((-x1 • v1) + (sum (x1 • v1 :: (List.zipWith (fun x v => x • v) (xs.eraseIdx i1) (vs.eraseIdx i1))))) := by rw [Sum.split_cons]
      _ = -x1i • ((-x1 • v1) + (sum (x1 • v1 :: ((List.zipWith (fun x v => x • v) xs vs).eraseIdx i1)))) := by rw [List.zipWith_eraseIdx]
      _ = -x1i • ((-x1 • v1) + (sum ((List.zipWith (fun x v => x • v) xs vs)))) := by
        rw [Sum.perm]
        rw [this]
        exact List.getElem_cons_eraseIdx_perm (List.zipWith (fun x v => x • v) xs vs) i1 h_i1LeZip
      _ = -x1i • (-x1 • v1) + 0 := by simp[h_sumEq0]
      _ = (x1i * x1) • v1 := by simp
      _ = (1:F) • v1 := by simp[<-x1_inv]
      _ = v1 := by simp


theorem lin_dep_from_v_is_lincomb_of_others [BEq V][LawfulBEq V][BEq F][EquivBEq F][LawfulBEq F]
        (vs: List V) (h: ∃ i1:Nat, ∃h:i1 < vs.length, ∃ ls : List F, ls.length = vs.length - 1 ∧ vs[i1] = sum (ls.zipWith (. • .) (vs.eraseIdx i1))) :
        ¬ @linear_independent F V F V vs := by
  have ⟨i1, h, xs, h_lsLen, h_repr⟩ := h
  let v1 := vs[i1]
  have : sum (List.zipWith (fun x v => x • v) xs (vs.eraseIdx i1)) + -v1 = 0 := by simp[v1, h_repr]
  let xs' := -1 :: xs
  let vs' := v1 :: vs.eraseIdx i1
  have : sum (List.zipWith (fun x v => x • v) xs' vs') = 0 := by simp[xs', vs', this,Sum.split_cons]
  let xs'' := xs.insertIdx i1 (-1)
  have h_i' : i1 <= vs.length - 1:= by grind -- todo: grind
  have h_len'' : xs''.length = vs.length := by
    simp[xs'', h_lsLen, h, List.length_insertIdx,h_i']
    grind --todo: grind
  have h_perm : List.Perm (xs''.zip vs) (xs'.zip vs') := by
    simp[xs',vs', xs'']
    sorry

  unfold linear_independent
  simp
  exists xs''
  constructor
  exact h_len''
  constructor
  sorry
  constructor
  sorry
  sorry




end VectorSpace
